export const BALANCE = 1840000;

export const WEEK = [
  ['Du', 40],
  ['Se', 65],
  ['Ch', 55],
  ['Pa', 80],
  ['Ju', 70],
  ['Sh', 100],
  ['Ya', 45],
];
export const MAX_WEEK = Math.max(...WEEK.map((d) => d[1]));

export const STATS = [
  {
    key: 'kln',
    value: '247',
    label: 'Bajarilgan ish',
    colorKey: 'green',
    icon: 'checkmark-circle',
  },
  {
    key: 'str',
    value: '4.9',
    label: "O'rtacha reyting",
    colorKey: 'gold',
    icon: 'star',
  },
  {
    key: 'rsp',
    value: '12 daq',
    label: "O'rtacha javob",
    colorKey: 'blue',
    icon: 'time',
  },
];

export const MY_CATEGORIES = [
  {
    id: 1,
    name: 'Santexnika',
    icon: 'wrench',
    price: '80 000',
    minPrice: '50 000',
    priceType: 'Ish uchun',
    experienceYears: 5,
    negotiable: true,
    isPrimary: true,
  },
  {
    id: 2,
    name: 'Isitish tizimlari',
    icon: 'radiator',
    price: '120 000',
    minPrice: '90 000',
    priceType: 'Ish uchun',
    experienceYears: 3,
    negotiable: false,
    isPrimary: false,
  },
  {
    id: 3,
    name: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    price: '150 000',
    minPrice: '100 000',
    priceType: 'Ish uchun',
    experienceYears: 4,
    negotiable: true,
    isPrimary: false,
  },
];

export const CLIENTS = {
  sardor: {
    id: 'c1',
    name: 'Sardor Aliyev',
    initial: 'S',
    color: '#3f7fd4',
    phone: '+998 90 123 45 67',
    location: 'Chilonzor tumani',
    fullAddress: "Chilonzor tumani, 19-mavze, 12-uy",
    memberSince: '2024-yil, mart',
    totalOrders: 2,
    totalSpent: '155 000',
    note: "Ish kunlari soat 18:00 dan keyin uyda bo'ladi. Kirish uchun domofon kodi: 245B.",
  },
  nodira: {
    id: 'c2',
    name: 'Nodira Karimova',
    initial: 'N',
    color: '#9b6cd1',
    phone: '+998 91 234 56 78',
    location: 'Yunusobod tumani',
    fullAddress: "Yunusobod tumani, Amir Temur ko'chasi, 45-uy",
    memberSince: '2025-yil, yanvar',
    totalOrders: 1,
    totalSpent: '450 000',
    note: "To'lovni faqat plastik karta orqali amalga oshiradi.",
  },
  javlon: {
    id: 'c3',
    name: 'Javlon Mirzayev',
    initial: 'J',
    color: '#2fa37a',
    phone: '+998 93 345 67 89',
    location: "Mirzo Ulug'bek tumani",
    fullAddress: "Mirzo Ulug'bek tumani, Buyuk Ipak Yo'li, 7-uy",
    memberSince: '2023-yil, iyun',
    totalOrders: 1,
    totalSpent: '620 000',
    note: "Uyda it bor — kirishdan oldin oldindan xabar berish kerak.",
  },
  otabek: {
    id: 'c4',
    name: 'Otabek Rustamov',
    initial: 'O',
    color: '#e0473a',
    phone: '+998 94 456 78 90',
    location: 'Sergeli tumani',
    fullAddress: 'Sergeli tumani, Bunyodkor shoh ko\'chasi, 3-uy',
    memberSince: '2025-yil, may',
    totalOrders: 1,
    totalSpent: '120 000',
    note: null,
  },
};

export const MY_WORKS = [
  {
    id: 1,
    title: 'Kran almashtirish',
    client: CLIENTS.sardor,
    rating: 5.0,
    date: '14-avgust, 2026',
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    price: '80 000',
    duration: '45 daqiqa',
    address: 'Chilonzor tumani',
    description:
      "Eskirgan va oqib turgan kran butunlay yangisiga almashtirildi. Barcha ulanishlar germetik qilib mahkamlandi, suv bosimi tekshirildi.",
    materials: ['Kran (Grohe)', 'Germetik lenta', 'Ulagichlar'],
    beforePhotos: [
      { icon: 'pipe-leak', label: 'Eski kran' },
      { icon: 'water-alert-outline', label: 'Suv oqishi' },
      { icon: 'wrench-clock', label: 'Zanglagan ulagich' },
      { icon: 'ruler-square', label: "O'lcham olish" },
    ],
    afterPhotos: [
      { icon: 'water-pump', label: 'Yangi kran' },
      { icon: 'link-variant', label: 'Germetik ulanish' },
      { icon: 'check-decagram', label: "Sinovdan o'tgan" },
      { icon: 'sparkles', label: 'Yakuniy ko\'rinish' },
    ],
    clientReview: {
      rating: 5,
      text: "Juda tez keldi va sifatli ishladi. Narxi ham kelishilgandek bo'ldi, rahmat!",
    },
    workerReview: {
      rating: 5,
      text: "Mijoz vaqtida uyda kutib oldi, to'lovni darhol amalga oshirdi. Yana ishlashdan xursand bo'laman.",
    },
  },
  {
    id: 2,
    title: 'Isitish tizimi montaji',
    client: CLIENTS.nodira,
    rating: 4.8,
    date: '9-avgust, 2026',
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    price: '450 000',
    duration: '3 soat',
    address: 'Yunusobod tumani',
    description:
      "Yashash xonasi va oshxonaga 2 ta radiator o'rnatildi, quvurlar ulandi va tizim bosim ostida sinovdan o'tkazildi.",
    materials: ['Radiator (2 dona)', 'Polipropilen quvur', 'Krepej'],
    beforePhotos: [
      { icon: 'radiator-disabled', label: 'Radiatorsiz xona' },
      { icon: 'pipe', label: 'Eski quvurlar' },
      { icon: 'ruler-square', label: "O'lchov olish" },
      { icon: 'wall', label: 'Devor tayyorlash' },
    ],
    afterPhotos: [
      { icon: 'radiator', label: "O'rnatilgan radiator" },
      { icon: 'pipe-wrench', label: 'Quvur ulanishi' },
      { icon: 'thermometer', label: 'Isitish testi' },
      { icon: 'check-decagram', label: 'Yakuniy natija' },
    ],
    clientReview: {
      rating: 5,
      text: "Muomilasi yoqdi, ishni ozgina kechikib boshlasa ham natija a'lo darajada.",
    },
    workerReview: {
      rating: 4,
      text: 'Mijoz aniq talab bilan kutib oldi, ish jarayoni qulay o\'tdi. To\'lov naqd amalga oshirildi.',
    },
  },
  {
    id: 3,
    title: "Vannaxona ta'miri",
    client: CLIENTS.javlon,
    rating: 5.0,
    date: '2-avgust, 2026',
    category: 'Sanitariya jihozlari',
    icon: 'shower',
    color: '#2fa37a',
    price: '620 000',
    duration: '1 kun',
    address: 'Mirzo Ulug\'bek tumani',
    description:
      "Vannaxonada unitaz va dush kabinasi to'liq yangilandi, kafel orasidagi choklar yangilanib, gidroizolyatsiya qayta ishlandi.",
    materials: ['Unitaz', 'Dush kabina', 'Gidroizolyatsiya', 'Silikon'],
    beforePhotos: [
      { icon: 'toilet', label: 'Eski unitaz' },
      { icon: 'grid-off', label: 'Yorilgan kafel' },
      { icon: 'shower-head', label: 'Eski dush' },
      { icon: 'water-alert-outline', label: 'Namlik izlari' },
    ],
    afterPhotos: [
      { icon: 'shower-head', label: 'Yangi dush kabina' },
      { icon: 'toilet', label: 'Yangi unitaz' },
      { icon: 'grid', label: 'Yangi kafel' },
      { icon: 'water-check-outline', label: 'Gidroizolyatsiya' },
      { icon: 'check-decagram', label: 'Yakunlangan ish' },
    ],
    clientReview: {
      rating: 4,
      text: "Yaxshi usta, lekin biroz band ekan, navbat kutishga to'g'ri keldi.",
    },
    workerReview: {
      rating: 4,
      text: "Ish hajmi katta edi, mijoz sabr bilan kutdi. Yakunda natijadan mamnun bo'lishdi.",
    },
  },
  {
    id: 4,
    title: 'Konditsioner tozalash',
    client: CLIENTS.otabek,
    rating: 4.9,
    date: '27-iyul, 2026',
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    price: '120 000',
    duration: '1 soat',
    address: 'Sergeli tumani',
    description:
      "Konditsionerning ichki va tashqi bloklari to'liq tozalandi, filtrlar yuvildi, freon darajasi tekshirildi.",
    materials: ['Tozalash eritmasi', 'Filtr yuvish vositasi'],
    beforePhotos: [
      { icon: 'air-filter', label: 'Kirlangan filtr' },
      { icon: 'weather-dust', label: 'Changlangan blok' },
    ],
    afterPhotos: [
      { icon: 'air-filter', label: 'Yangi filtr' },
      { icon: 'check-decagram', label: 'Tozalangan blok' },
    ],
    clientReview: null,
    workerReview: {
      rating: 5,
      text: "Mijoz do'stona munosabatda bo'ldi, kirish-chiqish qulay tashkil etildi.",
    },
  },
  {
    id: 5,
    title: "Suv isitgich o'rnatish",
    client: CLIENTS.sardor,
    rating: 4.9,
    date: '2-iyun, 2026',
    category: 'Santexnika',
    icon: 'water-boiler',
    color: '#3f7fd4',
    price: '75 000',
    duration: '1.5 soat',
    address: 'Chilonzor tumani',
    description:
      "Oshxonaga yangi protochniy suv isitgich o'rnatildi, elektr va suv ulanishi xavfsizlik talablariga muvofiq bajarildi.",
    materials: ['Suv isitgich', 'Elektr kabel', 'Ulagichlar'],
    beforePhotos: [
      { icon: 'water-off-outline', label: 'Isitgichsiz nuqta' },
      { icon: 'pipe', label: 'Eski ulanish' },
    ],
    afterPhotos: [
      { icon: 'water-boiler', label: "O'rnatilgan isitgich" },
      { icon: 'flash-outline', label: 'Elektr ulanishi' },
      { icon: 'check-decagram', label: 'Sinov muvaffaqiyatli' },
    ],
    clientReview: {
      rating: 5,
      text: "Ikkinchi marta chaqirdim, yana ham tez va aniq ishladi. Doim shu ustani tavsiya qilaman!",
    },
    workerReview: {
      rating: 5,
      text: "Doimiy mijoz, har doim aniq vaqtda kutib oladi va ishni tushunib turadi.",
    },
  },
];

// "Sizga tegishli e'lonlar" — platforma qoidasiga ko'ra har bir zakazchik
// faqat bitta ustaga bog'langan bo'ladi va shu ustadan boshqasiga buyurtma
// bera olmaydi. Shu sabab bu ro'yxatdagi barcha mijozlar aynan shu ustaga
// "faqat sizga" tarzida ulangan — umumiy bozordagi ochiq e'lonlardan farqli.
export const LINKED_ELONLAR = [
  {
    id: 1,
    client: CLIENTS.sardor,
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Vannaxonada trubadan suv oqmoqda',
    description:
      "Hammomdagi trubalardan suv oqyapti, tezroq kelib ko'rib berishingiz kerak.",
    address: 'Chilonzor tumani, 19-mavze',
    budget: '70 000 – 100 000',
    postedAgo: '12 daqiqa oldin',
    isNewClient: false,
  },
  {
    id: 2,
    client: CLIENTS.javlon,
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: 'Radiatorni tozalash va sozlash',
    description:
      "Isitish mavsumidan oldin barcha radiatorlarni tekshirib, tozalab berishingizni so'rayman.",
    address: "Mirzo Ulug'bek tumani",
    budget: '150 000',
    postedAgo: '40 daqiqa oldin',
    isNewClient: false,
  },
  {
    id: 3,
    client: { id: 'c5', name: 'Diyor Nazarov', initial: 'D', color: '#e0473a' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: "Yangi konditsioner o'rnatish",
    description:
      "Yotoqxonaga yangi split konditsioner o'rnatib berish kerak, jihoz tayyor turibdi.",
    address: 'Yashnobod tumani',
    budget: '200 000',
    postedAgo: '1 soat oldin',
    isNewClient: true,
  },
];

export const MY_REVIEWS = [
  {
    id: 1,
    workId: 1,
    name: 'Sardor Aliyev',
    rating: 5,
    time: '2 kun oldin',
    text: 'Juda tez keldi va sifatli ishladi. Narxi ham kelishilgandek bo\'ldi, rahmat!',
  },
  {
    id: 2,
    workId: 2,
    name: 'Nodira Karimova',
    rating: 5,
    time: '1 hafta oldin',
    text: "Muomilasi yoqdi, ishni ozgina kechikib boshlasa ham natija a'lo darajada.",
  },
  {
    id: 3,
    workId: 3,
    name: 'Javlon Mirzayev',
    rating: 4,
    time: '2 hafta oldin',
    text: "Yaxshi usta, lekin biroz band ekan, navbat kutishga to'g'ri keldi.",
  },
];

// "Yangi e'lonlar" — umumiy bozor: zakazchiklar tomonidan o'z kategoriyasi
// bo'yicha tushirilgan, hali hech qaysi ustaga bog'lanmagan ochiq e'lonlar.
// Bularni shu kategoriyadagi barcha ustalar ko'radi; qabul qilingandan
// so'nggina mijoz o'sha ustaga eksklyuziv bog'lanadi.
export const ALL_ELONLAR = [
  {
    id: 101,
    client: { name: 'Baxtiyor Yusupov', initial: 'B', color: '#3f7fd4' },
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Oshxonada kran singan',
    description: "Idish yuvish qismidagi kran singan, tezroq almashtirish kerak.",
    address: 'Yunusobod tumani',
    budget: '60 000 – 90 000',
    postedAgo: '5 daqiqa oldin',
  },
  {
    id: 102,
    client: { name: 'Zarina Nortojiyeva', initial: 'Z', color: '#e87a45' },
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: 'Kotyol ishlamayapti',
    description: "Uy sovib ketdi, kotyol yonmayapti — bugun kelib ko'rib berish kerak.",
    address: 'Yashnobod tumani',
    budget: '150 000 – 200 000',
    postedAgo: '10 daqiqa oldin',
  },
  {
    id: 103,
    client: { name: 'Davron Islomov', initial: 'D', color: '#9b6cd1' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: "2 xonaga konditsioner o'rnatish",
    description: "Ikkita split konditsioner sotib olindi, o'rnatib berish kerak.",
    address: 'Chilonzor tumani',
    budget: '350 000',
    postedAgo: '8 daqiqa oldin',
  },
  {
    id: 104,
    client: { name: 'Gulnora Tosheva', initial: 'G', color: '#2fa37a' },
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Unitaz tagidan suv sizmoqda',
    description: "Bir necha kundan beri tagidan asta suv sizib chiqyapti.",
    address: 'Chilonzor tumani',
    budget: '80 000',
    postedAgo: '18 daqiqa oldin',
  },
  {
    id: 105,
    client: { name: 'Aziz Rahimov', initial: 'A', color: '#e0473a' },
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: 'Radiatorlarni almashtirish',
    description: "Eskirgan 4 ta radiatorni yangisiga almashtirish kerak.",
    address: "Mirzo Ulug'bek tumani",
    budget: '400 000',
    postedAgo: '22 daqiqa oldin',
  },
  {
    id: 106,
    client: { name: 'Shahnoza Yusupova', initial: 'S', color: '#3f7fd4' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: 'Konditsioner freonini quyish',
    description: "Konditsioner soveutmay qoldi, freon quyilishi kerak.",
    address: 'Yunusobod tumani',
    budget: '130 000',
    postedAgo: '25 daqiqa oldin',
  },
  {
    id: 107,
    client: { name: 'Rustam Qodirov', initial: 'R', color: '#9b6cd1' },
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Yangi kvartirada santexnika ulash',
    description: "Yangi qurilgan kvartirada barcha santexnika jihozlarini ulab berish kerak.",
    address: 'Sergeli tumani',
    budget: '250 000',
    postedAgo: '35 daqiqa oldin',
  },
  {
    id: 108,
    client: { name: 'Feruza Mahmudova', initial: 'F', color: '#2fa37a' },
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: 'Isitish tizimida havo yig\'ilgan',
    description: "Radiatorlar isimayapti, tizimdan havo chiqarish kerak bo'lishi mumkin.",
    address: 'Shayxontohur tumani',
    budget: '90 000',
    postedAgo: '45 daqiqa oldin',
  },
  {
    id: 109,
    client: { name: 'Bekzod Nazarov', initial: 'B', color: '#e0473a' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: "Eski konditsionerni ko'chirish",
    description: "Konditsioner boshqa xonaga ko'chirilishi, quvurlar qayta tortilishi kerak.",
    address: 'Sergeli tumani',
    budget: '180 000',
    postedAgo: '40 daqiqa oldin',
  },
  {
    id: 110,
    client: { name: 'Malika Yoqubova', initial: 'M', color: '#3f7fd4' },
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Dush kabinasidan suv oqmoqda',
    description: "Dush kabinasi tagidan pol ustiga suv oqib chiqyapti.",
    address: 'Uchtepa tumani',
    budget: '70 000',
    postedAgo: '50 daqiqa oldin',
  },
  {
    id: 111,
    client: { name: 'Jasur Ergashev', initial: 'J', color: '#9b6cd1' },
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: 'Yangi qavat uchun isitish montaji',
    description: "Uy ustiga qurilgan yangi qavatga isitish tizimi o'tkazilishi kerak.",
    address: 'Olmazor tumani',
    budget: '600 000',
    postedAgo: '1 soat 10 daqiqa oldin',
  },
  {
    id: 112,
    client: { name: 'Madina Qosimova', initial: 'M', color: '#e87a45' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: "Ofisga 3 ta konditsioner o'rnatish",
    description: "Yangi ochilgan ofisga 3 ta split konditsioner o'rnatish kerak.",
    address: "Mirzo Ulug'bek tumani",
    budget: '900 000',
    postedAgo: '55 daqiqa oldin',
  },
  {
    id: 113,
    client: { name: 'Sherzod Aliqulov', initial: 'S', color: '#2fa37a' },
    category: 'Santexnika',
    icon: 'wrench',
    color: '#3f7fd4',
    title: 'Trubalarni izolyatsiya qilish',
    description: "Qish oldidan tashqi trubalarni sovuqdan izolyatsiya qilish kerak.",
    address: 'Bektemir tumani',
    budget: '120 000',
    postedAgo: '1 soat oldin',
  },
  {
    id: 114,
    client: { name: 'Nilufar Sattorova', initial: 'N', color: '#e0473a' },
    category: 'Isitish tizimlari',
    icon: 'radiator',
    color: '#e87a45',
    title: "Termostat o'rnatish",
    description: "Isitish tizimiga avtomatik termostat o'rnatib berish kerak.",
    address: 'Yakkasaroy tumani',
    budget: '110 000',
    postedAgo: '1 soat 30 daqiqa oldin',
  },
  {
    id: 115,
    client: { name: 'Otabek Toshpulatov', initial: 'O', color: '#3f7fd4' },
    category: "Konditsioner o'rnatish",
    icon: 'air-conditioner',
    color: '#9b6cd1',
    title: 'Konditsioner tozalash va servis',
    description: "Yozgi mavsum oldidan konditsionerni to'liq tozalab, servis qilish kerak.",
    address: 'Bektemir tumani',
    budget: '100 000',
    postedAgo: '2 soat oldin',
  },
];
